class DailyTips {
  static final Map<String, List<String>> localizedTips = {
    'en': [
      "Drink a glass of water slowly.",
      "Take 5 deep breaths right now.",
      "Stretch your arms above your head.",
      "Go for a short 5-minute walk.",
      "Stand up and shake out your body.",
      "Roll your shoulders back 10 times.",
      "Splash cold water on your face.",
      "Do 10 jumping jacks.",
      "Massage your temples gently.",
      "Take a warm shower.",
      "Eat a piece of fruit.",
      "Do gentle neck stretches.",
      "Wiggle your toes and feet.",
      "Take 3 big yawns.",
      "Hug yourself for 20 seconds.",
      "Clench and release your fists.",
      "Touch your toes (or try to).",
      "Drink some herbal tea.",
      "Close your eyes for 2 minutes.",
      "Step outside for fresh air.",
      "Do wall push-ups for 30 seconds.",
      "Eat something nourishing.",
      "Take off your shoes and walk barefoot.",
      "Tense and relax each muscle group.",
      "Wash your hands mindfully.",
      "Do some gentle yoga poses.",
      "Listen to your body's needs.",
      "Sit up straight and align your spine.",
      "Take a power nap (20 minutes max).",
      "Brush your teeth mindfully.",
      "Apply lotion to your hands slowly.",
      "Do 10 squats.",
      "Eat a healthy snack.",
      "Practice good posture.",
      "Take your vitamins.",
      "Drink green tea.",
      "Do ankle circles.",
      "Wash your face.",
      "Change into comfortable clothes.",
      "Do some light stretching.",
      "Take a bath.",
      "Eat vegetables today.",
      "Get some sunlight.",
      "Do gentle core exercises.",
      "Hydrate every hour.",
      "Practice box breathing.",
      "Take care of your hygiene.",
      "Do some resistance training.",
      "Eat breakfast mindfully.",
      "Rest when you need to.",
      "Move your body in any way.",
      "Drink lemon water.",
      "Do child's pose for 1 minute.",
      "Take a moment to yawn.",
      "Wear something that makes you feel good.",
      "Do some light cardio.",
      "Eat protein-rich food.",
      "Take breaks from sitting.",
      "Do palm presses for 30 seconds.",
      "Nourish your body well.",
      "Put your phone down for 10 minutes.",
      "Read one page of a book.",
      "Write down one thing you're grateful for.",
      "Do a 5-minute meditation.",
      "Unfollow accounts that don't serve you.",
      "Listen to calming music.",
      "Limit news consumption today.",
      "Do a brain dump in a journal.",
      "Learn something new for 10 minutes.",
      "Take a social media break.",
      "Practice mindfulness for 5 minutes.",
      "Solve a puzzle or riddle.",
      "Write a letter to yourself.",
      "Read something inspiring.",
      "Limit screen time before bed.",
      "Practice gratitude.",
      "Do a creative activity.",
      "Learn a new word.",
      "Listen to a podcast.",
      "Take a digital detox hour.",
      "Write down your feelings.",
      "Practice positive affirmations.",
      "Do a guided meditation.",
      "Read poetry.",
      "Set a small achievable goal.",
      "Practice visualization.",
      "Do a crossword puzzle.",
      "Learn a new skill.",
      "Journal for 10 minutes.",
      "Practice being present.",
      "Read something educational.",
      "Set healthy boundaries.",
      "Do a body scan meditation.",
      "Learn about something interesting.",
      "Practice self-compassion.",
      "Do a mindful activity.",
      "Read inspirational quotes.",
      "Practice cognitive reframing.",
      "Do a creative writing exercise.",
      "Learn about mental health.",
      "Practice acceptance.",
      "Do a memory exercise.",
      "Read about personal growth.",
      "Practice letting go.",
      "Do a concentration exercise.",
      "Learn a new fact.",
      "Practice non-judgment.",
      "Do a breathing exercise.",
      "Read about resilience.",
      "Practice self-awareness.",
      "Do a mental reset.",
      "Learn about emotional intelligence.",
      "Practice mindful observation.",
      "Do a reflection exercise.",
      "Read about self-improvement.",
      "Practice inner peace.",
      "Do a grounding exercise.",
      "Learn about coping strategies.",
      "Practice self-acceptance.",
      "Do a centering exercise.",
      "Allow yourself to feel your emotions.",
      "Cry if you need to.",
      "Laugh at something funny.",
      "Name your emotion right now.",
      "Talk to someone you trust.",
      "Write about your feelings.",
      "Allow yourself to be vulnerable.",
      "Practice self-validation.",
      "Express your needs.",
      "Set an emotional boundary.",
      "Acknowledge your feelings.",
      "Give yourself permission to rest.",
      "Practice emotional honesty.",
      "Share your story with someone.",
      "Allow yourself to be imperfect.",
      "Practice self-forgiveness.",
      "Acknowledge your struggles.",
      "Give yourself compassion.",
      "Express gratitude for yourself.",
      "Allow yourself to be human.",
      "Practice emotional release.",
      "Acknowledge your pain.",
      "Give yourself grace.",
      "Express love to yourself.",
      "Allow yourself to heal.",
      "Practice emotional awareness.",
      "Acknowledge your growth.",
      "Give yourself patience.",
      "Express kindness to yourself.",
      "Allow yourself to change.",
      "Practice emotional courage.",
      "Acknowledge your worth.",
      "Give yourself understanding.",
      "Express acceptance of yourself.",
      "Allow yourself to be seen.",
      "Practice emotional intelligence.",
      "Acknowledge your journey.",
      "Give yourself respect.",
      "Express pride in yourself.",
      "Allow yourself to receive love.",
      "Practice emotional balance.",
      "Acknowledge your resilience.",
      "Give yourself encouragement.",
      "Express belief in yourself.",
      "Allow yourself to thrive.",
      "Practice emotional freedom.",
      "Acknowledge your strength.",
      "Give yourself appreciation.",
      "Express trust in yourself.",
      "Allow yourself to flourish.",
      "Practice emotional wellness.",
      "Acknowledge your progress.",
      "Give yourself recognition.",
      "Express confidence in yourself.",
      "Allow yourself to succeed.",
      "Practice emotional health.",
      "Acknowledge your courage.",
      "Give yourself love.",
      "Express joy in being yourself.",
      "Allow yourself to be happy.",
      "Text a friend you haven't talked to.",
      "Call a loved one.",
      "Spend quality time with someone.",
      "Join a community or group.",
      "Reach out for support.",
      "Express appreciation to someone.",
      "Make plans with a friend.",
      "Connect with family.",
      "Join an online community.",
      "Share a meal with someone.",
      "Compliment someone genuinely.",
      "Listen actively to someone.",
      "Volunteer your time.",
      "Make a new friend.",
      "Reconnect with an old friend.",
      "Attend a social event.",
      "Join a class or workshop.",
      "Share your feelings with someone.",
      "Offer help to someone.",
      "Spend time in nature with others.",
      "Join a support group.",
      "Connect with like-minded people.",
      "Have a meaningful conversation.",
      "Express gratitude to someone.",
      "Participate in community activities.",
      "Reach out to someone struggling.",
      "Build a new relationship.",
      "Strengthen existing relationships.",
      "Share laughter with someone.",
      "Connect with your roots.",
      "Join a hobby group.",
      "Spend time with pets or animals.",
      "Attend a meetup.",
      "Connect online meaningfully.",
      "Share your story.",
      "Listen to someone's story.",
      "Join a cause you care about.",
      "Connect with mentors.",
      "Build your support network.",
      "Engage in social activities.",
      "Connect with your community.",
      "Share resources with others.",
      "Build collaborative relationships.",
      "Connect with nature lovers.",
      "Share knowledge with others.",
      "Build meaningful connections.",
      "Connect with creative people.",
      "Share experiences with others.",
      "Build supportive friendships.",
      "Connect with wellness communities.",
      "Share kindness with others.",
      "Build lasting relationships.",
      "Connect with positive people.",
      "Share love with others.",
      "Build healthy connections.",
      "Connect authentically.",
      "Share your gifts with others.",
      "Build community bonds.",
      "Connect with compassion.",
      "Share your light with others.",
      "Sit in silence for 5 minutes.",
      "Practice gratitude meditation.",
      "Spend time in nature.",
      "Reflect on your values.",
      "Practice loving-kindness meditation.",
      "Watch the sunrise or sunset.",
      "Connect with something bigger.",
      "Practice being present.",
      "Reflect on your purpose.",
      "Spend time alone peacefully.",
      "Practice acceptance meditation.",
      "Observe nature mindfully.",
      "Connect with your inner self.",
      "Practice surrender.",
      "Reflect on your growth.",
      "Spend time under the stars.",
      "Practice contemplation.",
      "Listen to the sounds of nature.",
      "Connect with your intuition.",
      "Practice letting go meditation.",
      "Reflect on life's beauty.",
      "Spend time by water.",
      "Practice peace meditation.",
      "Feel the earth beneath you.",
      "Connect with your breath.",
      "Practice awareness meditation.",
      "Reflect on interconnectedness.",
      "Spend time in sacred space.",
      "Practice compassion meditation.",
      "Observe the clouds.",
      "Connect with stillness.",
      "Practice presence.",
      "Reflect on impermanence.",
      "Spend time in quiet reflection.",
      "Practice unity meditation.",
      "Feel the wind on your skin.",
      "Connect with gratitude.",
      "Practice non-attachment.",
      "Reflect on your journey.",
      "Spend time in contemplative prayer.",
      "Practice forgiveness meditation.",
      "Observe natural cycles.",
      "Connect with your essence.",
      "Practice wholeness meditation.",
      "Reflect on life's mysteries.",
      "Spend time in spiritual practice.",
      "Practice acceptance.",
      "Feel connected to all life.",
      "Connect with your higher self.",
      "Practice transcendence meditation.",
      "Reflect on universal truths.",
      "Spend time in mindful awareness.",
      "Practice unity consciousness.",
      "Observe the present moment.",
      "Connect with divine energy.",
      "Practice enlightenment meditation.",
      "Reflect on eternal truths.",
      "Spend time in sacred silence.",
      "Practice spiritual awakening.",
      "Feel at one with existence.",
      "Draw or doodle for 10 minutes.",
      "Listen to your favorite song.",
      "Dance like nobody's watching.",
      "Sing in the shower.",
      "Try a new recipe.",
      "Take photos of beautiful things.",
      "Write a poem.",
      "Paint or color.",
      "Play a musical instrument.",
      "Try a new hobby.",
      "Watch something that makes you laugh.",
      "Create something with your hands.",
      "Listen to new music.",
      "Dance to upbeat music.",
      "Hum your favorite tune.",
      "Cook something delicious.",
      "Take artistic photos.",
      "Write creatively.",
      "Do crafts.",
      "Learn a new song.",
      "Explore a new interest.",
      "Watch comedy.",
      "Make something beautiful.",
      "Discover new artists.",
      "Move to music.",
      "Whistle a happy tune.",
      "Bake something sweet.",
      "Capture moments creatively.",
      "Journal creatively.",
      "Do DIY projects.",
      "Play with sounds.",
      "Try something new.",
      "Find humor in life.",
      "Express yourself artistically.",
      "Explore different genres.",
      "Express through movement.",
      "Make joyful sounds.",
      "Experiment in the kitchen.",
      "Create visual art.",
      "Tell stories.",
      "Build something.",
      "Enjoy musical exploration.",
      "Be adventurous.",
      "Laugh freely.",
      "Create without judgment.",
      "Listen to live music.",
      "Dance with abandon.",
      "Sing loudly.",
      "Try fusion cooking.",
      "Make photo collages.",
      "Write freely.",
      "Sculpt with clay.",
      "Compose music.",
      "Learn continuously.",
      "Watch feel-good content.",
      "Craft mindfully.",
      "Attend concerts.",
      "Move joyfully.",
      "Express vocally.",
      "Create culinary art.",
      "Design visually.",
      "Share your creativity.",
      "Play and create.",
      "Enjoy artistic expression.",
      "Celebrate life creatively."
    ],
    'hi': [
      "धीरे-धीरे एक गिलास पानी पिएं।",
      "अभी 5 गहरी सांसें लें।",
      "अपने हाथों को सिर के ऊपर खींचें (Stretch करें)।",
      "5 मिनट की छोटी सैर पर जाएं।",
      "खड़े हों और शरीर को थोड़ा हिलाएं।",
      "अपने कंधों को 10 बार पीछे की ओर घुमाएं।",
      "अपने चेहरे पर ठंडे पानी के छींटे मारें।",
      "10 बार जंपिंग जैक (Jumping Jacks) करें।",
      "अपनी कनपटी (Temples) की धीरे से मालिश करें।",
      "गर्म पानी से स्नान करें।",
      "एक फल खाएं।",
      "गर्दन के हल्के व्यायाम करें।",
      "अपने पैर की उंगलियों और पैरों को हिलाएं।",
      "3 बार लंबी उबासी लें।",
      "20 सेकंड के लिए खुद को गले लगाएं।",
      "अपनी मुट्ठियों को भींचें और छोड़ें।",
      "अपने पैर की उंगलियों को छूने की कोशिश करें।",
      "थोड़ी हर्बल चाय पिएं।",
      "2 मिनट के लिए अपनी आंखें बंद करें।",
      "ताजी हवा के लिए बाहर निकलें।",
      "30 सेकंड के लिए वॉल पुश-अप्स करें।",
      "कुछ पौष्टिक खाएं।",
      "अपने जूते उतारें और नंगे पैर चलें।",
      "प्रत्येक मांसपेशी समूह को तनाव दें और आराम दें।",
      "सचेत होकर अपने हाथ धोएं।",
      "कुछ हल्के योग आसन करें।",
      "अपने शरीर की जरूरतों को सुनें।",
      "सीधे बैठें और अपनी रीढ़ को सीधा रखें।",
      "थोड़ी देर के लिए झपकी लें (अधिकतम 20 मिनट)।",
      "सचेत होकर अपने दांत ब्रश करें।",
      "धीरे-धीरे अपने हाथों पर लोशन लगाएं।",
      "10 स्क्वैट्स (Squats) करें।",
      "एक स्वस्थ नाश्ता खाएं।",
      "उठने-बैठने का सही तरीका अपनाएं।",
      "अपने विटामिन लें।",
      "ग्रीन टी (Green tea) पिएं।",
      "टखनों को गोल घुमाएं।",
      "अपना चेहरा धोएं।",
      "आरामदायक कपड़े पहनें।",
      "हल्का स्ट्रेचिंग व्यायाम करें।",
      "स्नान करें।",
      "आज सब्जियां खाएं।",
      "थोड़ी धूप लें।",
      "हल्के कोर (Core) व्यायाम करें।",
      "हर घंटे पानी पिएं (Hydrate रहें)।",
      "बॉक्स ब्रीदिंग (Box breathing) का अभ्यास करें।",
      "अपनी स्वच्छता का ध्यान रखें।",
      "थोड़ा रेजिस्टेंस ट्रेनिंग (Resistance training) करें।",
      "सचेत होकर नाश्ता करें।",
      "ज़रूरत पड़ने पर आराम करें।",
      "किसी भी तरह से अपने शरीर को गतिशील रखें।",
      "नींबू पानी पिएं।",
      "1 मिनट के लिए चाइल्ड पोज (Child's pose) करें।",
      "उबासी लेने के लिए एक क्षण निकालें।",
      "कुछ ऐसा पहनें जिससे आपको अच्छा लगे।",
      "हल्का कार्डियो (Cardio) करें।",
      "प्रोटीन युक्त भोजन खाएं।",
      "बैठने से ब्रेक लें।",
      "30 सेकंड के लिए हथेली दबाने का प्रयास करें।",
      "अपने शरीर को अच्छी तरह पोषित करें।",
      "10 मिनट के लिए अपना फोन रख दें।",
      "किसी किताब का एक पेज पढ़ें।",
      "एक ऐसी चीज़ लिखें जिसके लिए आप आभारी हैं।",
      "5 मिनट का ध्यान (Meditation) करें।",
      "उन खातों को अनफॉलो करें जो आपके काम के नहीं हैं।",
      "शांत संगीत सुनें।",
      "आज समाचार कम देखें।",
      "जर्नल में अपने विचार लिखें।",
      "10 मिनट के लिए कुछ नया सीखें।",
      "सोशल मीडिया से ब्रेक लें।",
      "5 मिनट के लिए माइंडफुलनेस का अभ्यास करें।",
      "कोई पहेली हल करें।",
      "खुद को एक पत्र लिखें।",
      "कुछ प्रेरणादायक पढ़ें।",
      "सोने से पहले स्क्रीन का उपयोग कम करें।",
      "कृतज्ञता (Gratitude) का अभ्यास करें।",
      "एक रचनात्मक गतिविधि करें।",
      "एक नया शब्द सीखें।",
      "कोई पॉडकास्ट सुनें।",
      "एक घंटे के लिए डिजिटल डिटॉक्स (Digital detox) करें।",
      "अपनी भावनाएं लिखें।",
      "सकारात्मक पुष्टि (Positive affirmations) का अभ्यास करें।",
      "निर्देशित ध्यान (Guided meditation) करें।",
      "कविता पढ़ें।",
      "एक छोटा सा हासिल करने योग्य लक्ष्य निर्धारित करें।",
      "दृश्य कल्पना (Visualization) का अभ्यास करें।",
      "एक क्रॉसवर्ड पहेली हल करें।",
      "एक नया कौशल सीखें।",
      "10 मिनट के लिए जर्नल लिखें।",
      "वर्तमान क्षण में रहना सीखें।",
      "कुछ शैक्षिक पढ़ें।",
      "स्वस्थ सीमाएं निर्धारित करें।",
      "बॉडी स्कैन मेडिटेशन करें।",
      "किसी दिलचस्प चीज़ के बारे में जानें।",
      "आत्म-करुणा (Self-compassion) का अभ्यास करें।",
      "कोई माइंडफुल गतिविधि करें।",
      "प्रेरणादायक विचार पढ़ें।",
      "संज्ञानात्मक पुनर्गठन (Cognitive reframing) का अभ्यास करें।",
      "एक रचनात्मक लेखन अभ्यास करें।",
      "मानसिक स्वास्थ्य के बारे में जानें।",
      "स्वीकृति का अभ्यास करें।",
      "याददाश्त का कोई व्यायाम करें।",
      "व्यक्तिगत विकास के बारे में पढ़ें।",
      "छोड़ने (Letting go) का अभ्यास करें।",
      "एकाग्रता का कोई व्यायाम करें।",
      "एक नया तथ्य जानें।",
      "निर्णय न लेने (Non-judgment) का अभ्यास करें।",
      "सांस लेने का व्यायाम करें।",
      "लचीलेपन (Resilience) के बारे में पढ़ें।",
      "आत्म-जागरूकता (Self-awareness) का अभ्यास करें।",
      "एक मानसिक रीसेट करें।",
      "भावनात्मक बुद्धिमत्ता (Emotional intelligence) के बारे में जानें।",
      "सचेत अवलोकन (Mindful observation) का अभ्यास करें।",
      "चिंतन अभ्यास करें।",
      "आत्म-सुधार के बारे में पढ़ें।",
      "आंतरिक शांति का अभ्यास करें।",
      "ग्राउंडिंग व्यायाम (Grounding exercise) करें।",
      "मुकाबला करने की रणनीतियों (Coping strategies) के बारे में जानें।",
      "आत्म-स्वीकृति का अभ्यास करें।",
      "केंद्रित करने का अभ्यास (Centering exercise) करें।",
      "अपनी भावनाओं को महसूस करने दें।",
      "अगर ज़रूरत हो तो रो लें।",
      "किसी मज़ेदार चीज़ पर हंसें।",
      "अभी अपनी भावना को पहचानें।",
      "किसी ऐसे व्यक्ति से बात करें जिस पर आप भरोसा करते हैं।",
      "अपनी भावनाओं के बारे में लिखें।",
      "खुद को संवेदनशील होने दें।",
      "आत्म-पुष्टि (Self-validation) का अभ्यास करें।",
      "अपनी ज़रूरतें व्यक्त करें।",
      "एक भावनात्मक सीमा निर्धारित करें।",
      "अपनी भावनाओं को स्वीकार करें।",
      "खुद को आराम करने की अनुमति दें।",
      "भावनात्मक ईमानदारी का अभ्यास करें।",
      "किसी के साथ अपनी कहानी साझा करें।",
      "खुद को अपूर्ण होने की अनुमति दें।",
      "आत्म-क्षमा (Self-forgiveness) का अभ्यास करें।",
      "अपने संघर्षों को स्वीकार करें।",
      "खुद को करुणा दें।",
      "स्वयं के प्रति कृतज्ञता व्यक्त करें।",
      "खुद को इंसान होने दें।",
      "भावनात्मक रिलीज (Release) का अभ्यास करें।",
      "अपने दर्द को स्वीकार करें।",
      "खुद को अनुग्रह (Grace) दें।",
      "खुद के प्रति प्यार व्यक्त करें।",
      "खुद को ठीक होने दें।",
      "भावनात्मक जागरूकता का अभ्यास करें।",
      "अपने विकास को स्वीकार करें।",
      "खुद को धैर्य दें।",
      "खुद के प्रति दयालुता व्यक्त करें।",
      "खुद को बदलने की अनुमति दें।",
      "भावनात्मक साहस का अभ्यास करें।",
      "अपना मूल्य पहचानें।",
      "खुद को समझें।",
      "खुद की स्वीकृति व्यक्त करें।",
      "खुद को देखे जाने दें।",
      "भावनात्मक बुद्धिमत्ता का अभ्यास करें।",
      "अपनी यात्रा को स्वीकार करें।",
      "खुद को सम्मान दें।",
      "खुद पर गर्व व्यक्त करें।",
      "खुद को प्यार महसूस करने दें।",
      "भावनात्मक संतुलन का अभ्यास करें।",
      "अपने लचीलेपन को स्वीकार करें।",
      "खुद को प्रोत्साहन दें।",
      "खुद पर विश्वास व्यक्त करें।",
      "खुद को फलने-फूलने दें।",
      "भावनात्मक स्वतंत्रता का अभ्यास करें।",
      "अपनी ताकत स्वीकार करें।",
      "खुद की सराहना करें।",
      "खुद पर भरोसा रखें।",
      "खुद को विकसित होने दें।",
      "भावनात्मक तंदुरूस्ती का अभ्यास करें।",
      "अपनी प्रगति को स्वीकार करें।",
      "खुद को पहचान दें।",
      "खुद में आत्मविश्वास जगाएं।",
      "खुद को सफल होने दें।",
      "भावनात्मक स्वास्थ्य का अभ्यास करें।",
      "अपने साहस को स्वीकार करें।",
      "खुद को प्यार दें।",
      "खुद होने में खुशी महसूस करें।",
      "खुद को खुश रहने दें।",
      "किसी दोस्त को मैसेज करें जिससे बात नहीं हुई।",
      "किसी प्रियजन को फोन करें।",
      "किसी के साथ गुणवत्तापूर्ण समय बिताएं।",
      "किसी समुदाय या समूह में शामिल हों।",
      "मदद के लिए हाथ बढ़ाएं।",
      "किसी के प्रति सराहना व्यक्त करें।",
      "किसी दोस्त के साथ योजना बनाएं।",
      "परिवार के साथ जुड़ें।",
      "एक ऑनलाइन समुदाय में शामिल हों।",
      "किसी के साथ भोजन साझा करें।",
      "किसी की दिल से तारीफ करें।",
      "किसी की बात ध्यान से सुनें।",
      "अपना समय स्वयंसेवा में दें।",
      "एक नया दोस्त बनाएं।",
      "किसी पुराने दोस्त से फिर से जुड़ें।",
      "किसी सामाजिक कार्यक्रम में शामिल हों।",
      "किसी क्लास या वर्कशॉप में शामिल हों।",
      "किसी के साथ अपनी भावनाएं साझा करें।",
      "किसी को मदद की पेशकश करें।",
      "दूसरों के साथ प्रकृति में समय बिताएं।",
      "एक सहायता समूह (Support group) में शामिल हों।",
      "समान विचारधारा वाले लोगों से जुड़ें।",
      "एक सार्थक बातचीत करें।",
      "किसी के प्रति कृतज्ञता व्यक्त करें।",
      "सामुदायिक गतिविधियों में भाग लें।",
      "संघर्ष कर रहे किसी व्यक्ति की मदद करें।",
      "एक नया रिश्ता बनाएं।",
      "मौजूदा रिश्तों को मजबूत करें।",
      "किसी के साथ हंसें।",
      "अपनी जड़ों से जुड़ें।",
      "किसी हॉबी ग्रुप में शामिल हों।",
      "पालतू जानवरों या जानवरों के साथ समय बिताएं।",
      "किसी मीटअप (Meetup) में शामिल हों।",
      "ऑनलाइन सार्थक रूप से जुड़ें।",
      "अपनी कहानी साझा करें।",
      "किसी की कहानी सुनें।",
      "उस काम से जुड़ें जिसकी आप परवाह करते हैं।",
      "गुरुओं से जुड़ें।",
      "अपना सपोर्ट नेटवर्क बनाएं।",
      "सामाजिक गतिविधियों में शामिल हों।",
      "अपने समुदाय से जुड़ें।",
      "दूसरों के साथ संसाधन साझा करें।",
      "सहयोगात्मक रिश्ते बनाएं।",
      "प्रकृति प्रेमियों से जुड़ें।",
      "दूसरों के साथ ज्ञान साझा करें।",
      "सार्थक संबंध बनाएं।",
      "रचनात्मक लोगों से जुड़ें।",
      "दूसरों के साथ अनुभव साझा करें।",
      "सहयोगी मित्रता बनाएं।",
      "कल्याणकारी समुदायों से जुड़ें।",
      "दूसरों के साथ दयालुता साझा करें।",
      "स्थायी रिश्ते बनाएं।",
      "सकारात्मक लोगों से जुड़ें।",
      "दूसरों के साथ प्यार साझा करें।",
      "स्वस्थ संबंध बनाएं।",
      "प्रामाणिक रूप से जुड़ें।",
      "अपने उपहार दूसरों के साथ साझा करें।",
      "सामुदायिक बंधन बनाएं।",
      "करुणा के साथ जुड़ें।",
      "दूसरों के साथ अपना प्रकाश साझा करें।",
      "5 मिनट के लिए मौन बैठें।",
      "कृतज्ञता ध्यान का अभ्यास करें।",
      "प्रकृति में समय बिताएं।",
      "अपने मूल्यों पर चिंतन करें।",
      "करुणा ध्यान (Loving-kindness meditation) का अभ्यास करें।",
      "सूर्योदय या सूर्यास्त देखें।",
      "किसी बड़ी चीज़ से जुड़ें।",
      "वर्तमान में रहना सीखें।",
      "अपने उद्देश्य पर चिंतन करें।",
      "शांति से अकेले समय बिताएं।",
      "स्वीकृति ध्यान का अभ्यास करें।",
      "प्रकृति का ध्यानपूर्वक अवलोकन करें।",
      "अपने अंतर्मन से जुड़ें।",
      "समर्पण (Surrender) का अभ्यास करें।",
      "अपने विकास पर चिंतन करें।",
      "तारों के नीचे समय बिताएं।",
      "चिंतन (Contemplation) का अभ्यास करें।",
      "प्रकृति की आवाज़ें सुनें।",
      "अपने अंतर्ज्ञान (Intuition) से जुड़ें।",
      "छोड़ने वाले ध्यान (Letting go meditation) का अभ्यास करें।",
      "जीवन की सुंदरता पर चिंतन करें।",
      "पानी के पास समय बिताएं।",
      "शांति ध्यान का अभ्यास करें।",
      "अपने नीचे की धरती को महसूस करें।",
      "अपनी सांसों से जुड़ें।",
      "जागरूकता ध्यान का अभ्यास करें।",
      "परस्पर जुड़ाव पर चिंतन करें।",
      "पवित्र स्थान में समय बिताएं।",
      "करुणा ध्यान का अभ्यास करें।",
      "बादलों को देखें।",
      "शांति (Stillness) से जुड़ें।",
      "उपस्थिति (Presence) का अभ्यास करें।",
      "नश्वरता (Impermanence) पर चिंतन करें।",
      "शांत चिंतन में समय बिताएं।",
      "एकता ध्यान का अभ्यास करें।",
      "अपनी त्वचा पर हवा को महसूस करें।",
      "कृतज्ञता से जुड़ें।",
      "अनासक्ति (Non-attachment) का अभ्यास करें।",
      "अपनी यात्रा पर चिंतन करें।",
      "चिंतनशील प्रार्थना में समय बिताएं।",
      "क्षमा ध्यान का अभ्यास करें।",
      "प्राकृतिक चक्रों का अवलोकन करें।",
      "अपने सार (Essence) से जुड़ें।",
      "पूर्णता ध्यान (Wholeness meditation) का अभ्यास करें।",
      "जीवन के रहस्यों पर चिंतन करें।",
      "आध्यात्मिक अभ्यास में समय बिताएं।",
      "स्वीकृति का अभ्यास करें।",
      "सभी जीवन से जुड़ाव महसूस करें।",
      "अपने उच्च स्व (Higher self) से जुड़ें।",
      "उत्कृष्टता ध्यान (Transcendence meditation) का अभ्यास करें।",
      "सार्वभौमिक सत्यों पर चिंतन करें।",
      "सचेत जागरूकता में समय बिताएं।",
      "एकता चेतना का अभ्यास करें।",
      "वर्तमान क्षण का अवलोकन करें।",
      "दिव्य ऊर्जा से जुड़ें।",
      "आत्मज्ञान ध्यान (Enlightenment meditation) का अभ्यास करें।",
      "शाश्वत सत्यों पर चिंतन करें।",
      "पवित्र मौन में समय बिताएं।",
      "आध्यात्मिक जागृति का अभ्यास करें।",
      "अस्तित्व के साथ एक महसूस करें।",
      "10 मिनट के लिए चित्रकारी या डूडलिंग करें।",
      "अपना पसंदीदा गाना सुनें।",
      "ऐसे नाचें जैसे कोई देख नहीं रहा हो।",
      "शावर में गाना गाएं।",
      "एक नई रेसिपी आज़माएं।",
      "सुंदर चीज़ों के फोटो लें।",
      "एक कविता लिखें।",
      "पेंट या रंग करें।",
      "एक वाद्य यंत्र बजाएं।",
      "एक नया शौक आज़माएं।",
      "कुछ ऐसा देखें जिससे आप हंसें।",
      "अपने हाथों से कुछ बनाएं।",
      "नया संगीत सुनें।",
      "उत्साहजनक संगीत पर नाचें।",
      "अपनी पसंदीदा धुन गुनगुनाएं।",
      "कुछ स्वादिष्ट पकाएं।",
      "कलात्मक फोटो लें।",
      "रचनात्मक तरीके से लिखें।",
      "शिल्प (Crafts) करें।",
      "एक नया गाना सीखें।",
      "एक नई रुचि की तलाश करें।",
      "कॉमेडी देखें।",
      "कुछ सुंदर बनाएं।",
      "नए कलाकारों की खोज करें।",
      "संगीत के साथ थिरकें।",
      "एक सुखद धुन बजाएं।",
      "कुछ मीठा पकाएं।",
      "क्षणों को रचनात्मक रूप से कैद करें।",
      "रचनात्मक रूप से जर्नल लिखें।",
      "DIY प्रोजेक्ट करें।",
      "आवाज़ों के साथ खेलें।",
      "कुछ नया आज़माएं।",
      "जीवन में हास्य खोजें।",
      "कलात्मक रूप से खुद को व्यक्त करें।",
      "विभिन्न शैलियों का पता लगाएं।",
      "आंदोलन (Movement) के माध्यम से व्यक्त करें।",
      "आनंदमयी आवाज़ें निकालें।",
      "रसोई में प्रयोग करें।",
      "दृश्य कला बनाएं।",
      "कहानियां सुनाएं।",
      "कुछ बनायें।",
      "संगीत की खोज का आनंद लें।",
      "साहसी बनें।",
      "खुलकर हंसें।",
      "बिना किसी निर्णय के निर्माण करें।",
      "लाइव संगीत सुनें।",
      "खुलकर नाचें।",
      "ज़ोर से गाएं।",
      "फ्यूजन कुकिंग आज़माएं।",
      "फोटो कोलाज बनाएं।",
      "खुलकर लिखें।",
      "मिट्टी से आकृतियां बनाएं।",
      "संगीत लिखें।",
      "लगातार सीखते रहें।",
      "अच्छा महसूस कराने वाली चीज़ें देखें।",
      "सचेत रूप से शिल्प करें।",
      "संगीत कार्यक्रमों में शामिल हों।",
      "खुशी से झूम उठें।",
      "अपनी आवाज़ से व्यक्त करें।",
      "पाक कला (Culinary art) बनाएं।",
      "दृश्य रूप से डिज़ाइन करें।",
      "अपनी रचनात्मकता साझा करें।",
      "खेलें और बनायें।",
      "कलात्मक अभिव्यक्ति का आनंद लें।",
      "जीवन का रचनात्मक रूप से जश्न मनाएं।"
    ],
    'hn': [
      "Dheere se ek glass paani piyein.",
      "Abhi 5 gehri saansein lein.",
      "Apne haath sir ke upar stretch karein.",
      "5 minute ki walk par jayein.",
      "Khade ho kar body ko shake karein.",
      "Shoulders ko 10 baar roll karein.",
      "Chehre par thanda paani daalein.",
      "10 jumping jacks karein.",
      "Garam paani se nahayein.",
      "Ek phal khayein."
    ],
  };

  static String today(String lang) {
    final dayOfYear =
        DateTime.now().difference(DateTime(DateTime.now().year, 1, 1)).inDays;
    final tips = localizedTips[lang] ?? localizedTips['en']!;
    return tips[dayOfYear % tips.length];
  }
}
