class DailyThoughts {
  static final Map<String, List<String>> localizedThoughts = {
    'en': [
      "You are allowed to take things slowly.",
      "Not every bad day is a bad life.",
      "It's okay to rest. You are not lazy.",
      "You don't have to fix everything today.",
      "Even being here is enough.",
      "Your feelings are valid, even if others don't understand.",
      "Progress is not always visible.",
      "You are doing better than you think.",
      "It's okay to ask for help.",
      "You deserve gentleness, especially from yourself.",
      "Small steps are still steps forward.",
      "You are not broken. You are human.",
      "It's okay to not be okay.",
      "Your struggles do not define you.",
      "You have survived 100% of your worst days.",
      "Healing is not linear.",
      "You are worthy of love and care.",
      "It's okay to set boundaries.",
      "You don't owe anyone an explanation.",
      "Your pace is perfect for you.",
      "You are allowed to change your mind.",
      "It's okay to prioritize yourself.",
      "You are enough, just as you are.",
      "Your mental health matters.",
      "You are not a burden.",
      "It's okay to feel your emotions.",
      "You are stronger than you know.",
      "You deserve patience and understanding.",
      "It's okay to start over.",
      "You are worthy of good things.",
      "Every storm runs out of rain.",
      "Tomorrow is a new beginning.",
      "You have come so far already.",
      "This feeling is temporary.",
      "You have overcome hard things before.",
      "There is light at the end of this tunnel.",
      "You are growing, even when it doesn't feel like it.",
      "Better days are coming.",
      "You are more resilient than you realize.",
      "This too shall pass.",
      "You are capable of amazing things.",
      "Your story isn't over yet.",
      "You have the strength to get through this.",
      "Every day is a fresh start.",
      "You are writing your own story.",
      "You have the power to create change.",
      "Your journey matters.",
      "You are learning and growing.",
      "You can do hard things.",
      "You are not alone in this.",
      "You have people who care about you.",
      "Your presence makes a difference.",
      "You are valued and appreciated.",
      "You have so much to offer.",
      "Your light shines, even in darkness.",
      "You are a work in progress, and that's beautiful.",
      "You are deserving of happiness.",
      "Your best days are still ahead.",
      "You are worthy of a beautiful life.",
      "You have the courage to keep going.",
      "Breathe in peace, breathe out tension.",
      "This moment is all you need to handle.",
      "You are safe right now.",
      "Let go of what you cannot control.",
      "Be present in this moment.",
      "You are exactly where you need to be.",
      "Peace is found within you.",
      "You can choose calm.",
      "This moment will pass.",
      "You are grounded and centered.",
      "Let yourself feel without judgment.",
      "You are learning to be gentle with yourself.",
      "Stillness is a form of strength.",
      "You can handle whatever comes.",
      "You are finding your way.",
      "Trust the process of your healing.",
      "You are learning to let go.",
      "Peace comes from within.",
      "You are allowed to feel at ease.",
      "You are safe in this moment.",
      "You are learning to be present.",
      "Calm is always available to you.",
      "You can return to your breath.",
      "You are finding your balance.",
      "You are learning to trust yourself.",
      "You are discovering inner peace.",
      "You are allowed to just be.",
      "You are learning to accept what is.",
      "You are cultivating peace within.",
      "You are enough in this moment.",
      "Change is a sign you are growing.",
      "You are evolving every day.",
      "Growth happens in uncomfortable places.",
      "You are becoming who you're meant to be.",
      "Every experience teaches you something.",
      "You are learning valuable lessons.",
      "Mistakes are part of growth.",
      "You are allowed to outgrow things.",
      "You are constantly learning.",
      "Change means you are moving forward.",
      "You are transforming for the better.",
      "You are discovering new strengths.",
      "Growth requires patience.",
      "You are expanding your horizons.",
      "You are embracing new possibilities.",
      "You are learning to adapt.",
      "You are becoming stronger.",
      "You are developing resilience.",
      "You are growing through what you're going through.",
      "You are learning from every challenge.",
      "You are becoming more aware.",
      "You are discovering who you truly are.",
      "You are evolving beautifully.",
      "You are learning to trust the journey.",
      "You are growing at your own pace.",
      "You are becoming more authentic.",
      "You are learning to embrace change.",
      "You are discovering your potential.",
      "You are growing into your best self.",
      "You are learning to love the process.",
      "You deserve love and kindness.",
      "You are worthy of self-compassion.",
      "You are learning to love yourself.",
      "You deserve to treat yourself well.",
      "You are worthy of your own affection.",
      "You deserve to be gentle with yourself.",
      "You are learning to accept yourself.",
      "You deserve to celebrate yourself.",
      "You are worthy of self-care.",
      "You deserve to honor your needs.",
      "You are learning to appreciate yourself.",
      "You deserve to be proud of yourself.",
      "You are worthy of forgiveness.",
      "You deserve to be kind to yourself.",
      "You are learning to embrace who you are.",
      "You deserve to love yourself unconditionally.",
      "You are worthy of your own respect.",
      "You deserve to be your own friend.",
      "You are learning to value yourself.",
      "You deserve to acknowledge your worth.",
      "You are worthy of happiness and joy.",
      "You deserve to celebrate your victories.",
      "You are learning to be patient with yourself.",
      "You deserve to give yourself grace.",
      "You are worthy of understanding.",
      "You deserve to be gentle with your heart.",
      "You are learning to trust yourself.",
      "You deserve to believe in yourself.",
      "You are worthy of good things.",
      "You deserve to live fully.",
      "You have the courage to face today.",
      "You are braver than you believe.",
      "You have strength within you.",
      "You can handle more than you think.",
      "You have overcome so much already.",
      "You are building strength every day.",
      "You have the courage to keep trying.",
      "You are stronger after every challenge.",
      "You have the power within you.",
      "You are capable of great resilience.",
      "You have the strength to endure.",
      "You are finding courage in vulnerability.",
      "You have inner strength you haven't tapped yet.",
      "You are learning to be brave.",
      "You have the courage to be yourself.",
      "You are stronger than your struggles.",
      "You have the strength to rise again.",
      "You are learning to trust your strength.",
      "You have courage in your heart.",
      "You are building mental fortitude.",
      "You have the power to persevere.",
      "You are learning to stand tall.",
      "You have strength in your spirit.",
      "You are braver with each step.",
      "You have the courage to heal.",
      "You are stronger than you know.",
      "You have resilience in your soul.",
      "You are learning to be fearless.",
      "You have the strength to continue.",
      "You are courageous simply by being here.",
      "You deserve to experience joy.",
      "There is beauty around you.",
      "You can find reasons to smile.",
      "You are allowed to feel happy.",
      "There are good things coming.",
      "You deserve moments of peace.",
      "You can appreciate small joys.",
      "You are worthy of happiness.",
      "There is light in your life.",
      "You can choose to see the good.",
      "You deserve to feel grateful.",
      "You are surrounded by blessings.",
      "You can find joy in simple things.",
      "You are worthy of beautiful moments.",
      "There is goodness in your life.",
      "You can appreciate where you are.",
      "You deserve to feel contentment.",
      "You are experiencing growth.",
      "You can celebrate small wins.",
      "You are worthy of celebration.",
      "There are reasons to be hopeful.",
      "You can embrace positive moments.",
      "You deserve to feel at peace.",
      "You are surrounded by love.",
      "You can find gratitude daily.",
      "You are worthy of good experiences.",
      "There is joy waiting for you.",
      "You can appreciate your journey.",
      "You deserve to feel fulfilled.",
      "You are experiencing life beautifully.",
      "You are not alone in this.",
      "There are people who care.",
      "You deserve support and help.",
      "You can reach out when needed.",
      "You are worthy of connection.",
      "You deserve to be heard.",
      "You can share your struggles.",
      "You are worthy of understanding.",
      "You deserve compassion from others.",
      "You can ask for what you need.",
      "You are worthy of community.",
      "You deserve to feel supported.",
      "You can lean on others.",
      "You are worthy of friendship.",
      "You deserve to be seen.",
      "You can connect with others.",
      "You are worthy of kindness.",
      "You deserve to feel included.",
      "You can build meaningful relationships.",
      "You are worthy of love.",
      "You deserve to feel valued.",
      "You can give and receive support.",
      "You are worthy of belonging.",
      "You deserve to feel connected.",
      "You can trust in relationships.",
      "You are worthy of care.",
      "You deserve to be understood.",
      "You can find your tribe.",
      "You are worthy of companionship.",
      "You deserve healthy connections.",
      "Your life has purpose.",
      "You make a difference.",
      "Your presence matters.",
      "You have unique gifts to offer.",
      "Your story is important.",
      "You are here for a reason.",
      "Your journey has meaning.",
      "You contribute to the world.",
      "Your existence is valuable.",
      "You have a role to play.",
      "Your life touches others.",
      "You are making an impact.",
      "Your voice deserves to be heard.",
      "You have something to contribute.",
      "Your experiences matter.",
      "You are creating your legacy.",
      "Your actions have meaning.",
      "You are part of something bigger.",
      "Your life has significance.",
      "You are worthy of a meaningful life.",
      "Your perspective is valuable.",
      "You are discovering your purpose.",
      "Your presence is a gift.",
      "You are living with intention.",
      "Your journey inspires others.",
      "You are making your mark.",
      "Your life is meaningful.",
      "You are creating positive change.",
      "Your existence matters deeply.",
      "You are fulfilling your purpose.",
      "You can let go of what no longer serves you.",
      "You deserve to feel free.",
      "You can release old patterns.",
      "You are allowed to move on.",
      "You deserve to feel unburdened.",
      "You can forgive yourself.",
      "You are learning to let go.",
      "You deserve freedom from guilt.",
      "You can release what weighs you down.",
      "You are allowed to feel light.",
      "You deserve to break free.",
      "You can leave the past behind.",
      "You are learning to release control.",
      "You deserve to feel liberated.",
      "You can let go of perfection.",
      "You are allowed to surrender.",
      "You deserve freedom from shame.",
      "You can release expectations.",
      "You are learning to forgive.",
      "You deserve to feel unburdened.",
      "You can let go of judgment.",
      "You are allowed to be free.",
      "You deserve release from pain.",
      "You can surrender what you cannot change.",
      "You are learning to accept.",
      "You deserve freedom to be yourself.",
      "You can release old wounds.",
      "You are allowed to heal.",
      "You deserve to feel at peace.",
      "You can let go and trust.",
      "Every day teaches you something new.",
      "You are gaining wisdom.",
      "You learn from every experience.",
      "You are becoming more aware.",
      "You grow through challenges.",
      "You are learning about yourself.",
      "You gain insight from struggles.",
      "You are developing understanding.",
      "You learn through both joy and pain.",
      "You are becoming wiser.",
      "You grow from mistakes.",
      "You are learning life lessons.",
      "You gain clarity through experience.",
      "You are expanding your knowledge.",
      "You learn from every moment.",
      "You are developing perspective.",
      "You gain strength through learning.",
      "You are becoming more conscious.",
      "You learn what truly matters.",
      "You are growing in awareness.",
      "You gain wisdom through reflection.",
      "You are learning to trust.",
      "You discover truth through experience.",
      "You are becoming more mindful.",
      "You learn from every season.",
      "You are gaining deeper understanding.",
      "You grow through contemplation.",
      "You are learning what you need.",
      "You gain insight through stillness.",
      "You are becoming who you're meant to be.",
      "You deserve to celebrate how far you've come.",
      "You have accomplished so much.",
      "You are worthy of recognition.",
      "You deserve to honor your journey.",
      "You have grown tremendously.",
      "You are worthy of celebration.",
      "You deserve to acknowledge your progress.",
      "You have overcome incredible obstacles.",
      "You are worthy of pride.",
      "You deserve to celebrate yourself.",
      "You have achieved more than you realize.",
      "You are worthy of applause.",
      "You deserve to recognize your strength.",
      "You have made it through so much.",
      "You are worthy of congratulations.",
      "You deserve to feel proud.",
      "You have shown remarkable resilience.",
      "You are worthy of honor.",
      "You deserve to celebrate your victories.",
      "You have demonstrated courage.",
      "You are worthy of praise.",
      "You deserve to acknowledge your worth.",
      "You have proven your strength.",
      "You are worthy of appreciation.",
      "You deserve to celebrate your existence.",
      "You have created a beautiful journey.",
      "You are worthy of love and admiration.",
      "You deserve to feel accomplished.",
      "You have made it this far.",
      "You are worthy of all good things.",
      "You have completed another day.",
      "You are here, and that is enough.",
      "You deserve to celebrate this moment.",
      "You have come full circle.",
      "You are worthy of a fresh start tomorrow."
    ],
    'hi': [
      "आपको चीजों को धीरे-धीरे करने की अनुमति है।",
      "हर बुरा दिन खराब जीवन नहीं होता।",
      "आराम करना ठीक है। आप आलसी नहीं हैं।",
      "आपको आज ही सब कुछ ठीक करने की ज़रूरत नहीं है।",
      "यहाँ होना ही काफी है।",
      "आपकी भावनाएं वैध हैं, भले ही दूसरे न समझें।",
      "प्रगति हमेशा दिखाई नहीं देती।",
      "आप जितना सोचते हैं उससे बेहतर कर रहे हैं।",
      "मदद मांगना ठीक है।",
      "आप कोमलता के हकदार हैं, खासकर खुद से।",
      "छोटे कदम भी आगे बढ़ने वाले कदम हैं।",
      "आप टूटे हुए नहीं हैं। आप इंसान हैं।",
      "ठीक न होना भी ठीक है।",
      "आपका संघर्ष आपको परिभाषित नहीं करता।",
      "आप अपने सबसे बुरे दिनों में से 100% से बच गए हैं।",
      "ठीक होना एक सीधी रेखा नहीं है।",
      "आप प्यार और देखभाल के पात्र हैं।",
      "सीमाएं तय करना ठीक है।",
      "आपका किसी को स्पष्टीकरण देना नहीं बनता।",
      "आपकी गति आपके लिए बिल्कुल सही है।",
      "आपको अपना मन बदलने की अनुमति है।",
      "खुद को प्राथमिकता देना ठीक है।",
      "आप जैसे हैं, वैसे ही पर्याप्त हैं।",
      "आपका मानसिक स्वास्थ्य मायने रखता है।",
      "आप बोझ नहीं हैं।",
      "अपनी भावनाओं को महसूस करना ठीक है।",
      "आप जितना जानते हैं उससे कहीं अधिक मजबूत हैं।",
      "आप धैर्य और समझ के पात्र हैं।",
      "फिर से शुरू करना ठीक है।",
      "आप अच्छी चीजों के पात्र हैं।",
      "हर तूफान का पानी खत्म हो जाता है।",
      "कल एक नई शुरुआत है।",
      "आप पहले ही इतनी दूर आ चुके हैं।",
      "यह अहसास अस्थायी है।",
      "आपने पहले भी कठिन चीजों पर विजय प्राप्त की है।",
      "इस सुरंग के अंत में रोशनी है।",
      "आप बढ़ रहे हैं, भले ही ऐसा महसूस न हो।",
      "बेहतर दिन आ रहे हैं।",
      "आप जितना महसूस करते हैं उससे अधिक लचीले हैं।",
      "यह भी बीत जाएगा।",
      "आप अद्भुत चीजें करने में सक्षम हैं।",
      "आपकी कहानी अभी खत्म नहीं हुई है।",
      "आपके पास इससे निपटने की ताकत है।",
      "हर दिन एक नई शुरुआत है।",
      "आप अपनी कहानी खुद लिख रहे हैं।",
      "आपके पास बदलाव लाने की शक्ति है।",
      "आपकी यात्रा मायने रखती है।",
      "आप सीख रहे हैं और बढ़ रहे हैं।",
      "आप कठिन काम कर सकते हैं।",
      "आप इसमें अकेले नहीं हैं।",
      "आपके पास ऐसे लोग हैं जो आपकी परवाह करते हैं।",
      "आपकी उपस्थिति से फर्क पड़ता है।",
      "आप मूल्यवान हैं और आपकी सराहना की जाती है।",
      "आपके पास देने के लिए बहुत कुछ है।",
      "आपका प्रकाश अंधेरे में भी चमकता है।",
      "आप प्रगति पर हैं, और वह सुंदर है।",
      "आप खुशी के पात्र हैं।",
      "आपके सबसे अच्छे दिन अभी आने बाकी हैं।",
      "आप एक सुंदर जीवन के पात्र हैं।",
      "आपके पास आगे बढ़ते रहने का साहस है।",
      "शांति में सांस लें, तनाव बाहर निकालें।",
      "यह क्षण वह सब है जिसे आपको संभालना है।",
      "आप अभी सुरक्षित हैं।",
      "उसे छोड़ दें जिसे आप नियंत्रित नहीं कर सकते।",
      "इस क्षण में उपस्थित रहें।",
      "आप वहीं हैं जहाँ आपको होने की ज़रूरत है।",
      "शांति आपके भीतर पाई जाती है।",
      "आप शांति चुन सकते हैं।",
      "यह क्षण बीत जाएगा।",
      "आप स्थिर और केंद्रित हैं।",
      "बिना निर्णय के खुद को महसूस करने दें।",
      "आप खुद के प्रति कोमल होना सीख रहे हैं।",
      "स्थिरता भी शक्ति का एक रूप है।",
      "जो भी आए आप उसे संभाल सकते हैं।",
      "आप अपना रास्ता खोज रहे हैं।",
      "अपने ठीक होने की प्रक्रिया पर विश्वास करें।",
      "आप छोड़ना सीख रहे हैं।",
      "शांति भीतर से आती है।",
      "आपको सहज महसूस करने की अनुमति है।",
      "आप इस क्षण में सुरक्षित हैं।",
      "आप उपस्थित रहना सीख रहे हैं।",
      "शांति हमेशा आपके लिए उपलब्ध है।",
      "आप अपनी सांसों पर लौट सकते हैं।",
      "आप अपना संतुलन पा रहे हैं।",
      "आप खुद पर विश्वास करना सीख रहे हैं।",
      "आप आंतरिक शांति की खोज कर रहे हैं।",
      "आपको बस होने की अनुमति है।",
      "आप जो है उसे स्वीकार करना सीख रहे हैं।",
      "आप भीतर शांति विकसित कर रहे हैं।",
      "आप इस क्षण में पर्याप्त हैं।",
      "बदलाव इस बात का संकेत है कि आप बढ़ रहे हैं।",
      "आप हर दिन विकसित हो रहे हैं।",
      "विकास असहज जगहों पर होता है।",
      "आप वह बन रहे हैं जो आपको होना चाहिए।",
      "हर अनुभव आपको कुछ सिखाता है।",
      "आप बहुमूल्य सबक सीख रहे हैं।",
      "गलतियां विकास का हिस्सा हैं।",
      "आपको चीजों से आगे बढ़ने की अनुमति है।",
      "आप लगातार सीख रहे हैं।",
      "बदलाव का मतलब है कि आप आगे बढ़ रहे हैं।",
      "आप बेहतरी के लिए बदल रहे हैं।",
      "आप नई खूबियों की खोज कर रहे हैं।",
      "विकास के लिए धैर्य की आवश्यकता होती है।",
      "आप अपने क्षितिज का विस्तार कर रहे हैं।",
      "आप नई संभावनाओं को अपना रहे हैं।",
      "आप अनुकूलन करना सीख रहे हैं।",
      "आप मजबूत हो रहे हैं।",
      "आप लचीलापन विकसित कर रहे हैं।",
      "आप उससे बढ़ रहे हैं जिससे आप गुजर रहे हैं।",
      "आप हर चुनौती से सीख रहे हैं।",
      "आप अधिक जागरूक हो रहे हैं।",
      "आप जान रहे हैं कि आप वास्तव में कौन हैं।",
      "आप खूबसूरती से विकसित हो रहे हैं।",
      "आप यात्रा पर भरोसा करना सीख रहे हैं।",
      "आप अपनी गति से बढ़ रहे हैं।",
      "आप अधिक प्रामाणिक बन रहे हैं।",
      "आप बदलाव को अपनाना सीख रहे हैं।",
      "आप अपनी क्षमता की खोज कर रहे हैं।",
      "आप अपने सर्वोत्तम स्वरूप में विकसित हो रहे हैं।",
      "आप प्रक्रिया को प्यार करना सीख रहे हैं।",
      "आप प्यार और दया के पात्र हैं।",
      "आप आत्म-दया के पात्र हैं।",
      "आप खुद से प्यार करना सीख रहे हैं।",
      "आप खुद के साथ अच्छा व्यवहार करने के पात्र हैं।",
      "आप अपने स्वयं के स्नेह के पात्र हैं।",
      "आप खुद के प्रति कोमल होने के पात्र हैं।",
      "आप खुद को स्वीकार करना सीख रहे हैं।",
      "आप खुद का जश्न मनाने के पात्र हैं।",
      "आप आत्म-देखभाल के पात्र हैं।",
      "आप अपनी जरूरतों का सम्मान करने के पात्र हैं।",
      "आप खुद की सराहना करना सीख रहे हैं।",
      "आप खुद पर गर्व करने के पात्र हैं।",
      "आप क्षमा के पात्र हैं।",
      "आप खुद के प्रति दयालु होने के पात्र हैं।",
      "आप यह अपनाना सीख रहे हैं कि आप कौन हैं।",
      "आप बिना शर्त खुद से प्यार करने के पात्र हैं।",
      "आप अपने स्वयं के सम्मान के पात्र हैं।",
      "आप अपना खुद का दोस्त बनने के हकदार हैं।",
      "आप खुद को महत्व देना सीख रहे हैं।",
      "आप अपना मूल्य पहचानने के पात्र हैं।",
      "आप खुशी और आनंद के पात्र हैं।",
      "आप अपनी जीत का जश्न मनाने के पात्र हैं।",
      "आप खुद के साथ धैर्य रखना सीख रहे हैं।",
      "आप खुद को अनुग्रह देने के पात्र हैं।",
      "आप समझ के पात्र हैं।",
      "आप अपने दिल के प्रति कोमल होने के पात्र हैं।",
      "आप खुद पर भरोसा करना सीख रहे हैं।",
      "आप खुद पर विश्वास करने के पात्र हैं।",
      "आप अच्छी चीजों के पात्र हैं।",
      "आप पूरी तरह जीने के पात्र हैं।",
      "आपमें आज का सामना करने का साहस है।",
      "आप जितना विश्वास करते हैं उससे कहीं अधिक बहादुर हैं।",
      "आपके भीतर ताकत है।",
      "आप जितना सोचते हैं उससे अधिक संभाल सकते हैं।",
      "आपने पहले ही बहुत कुछ हासिल कर लिया है।",
      "आप हर दिन ताकत बना रहे हैं।",
      "आपमें कोशिश करते रहने का साहस है।",
      "आप हर चुनौती के बाद और मजबूत होते हैं।",
      "शक्ति आपके भीतर है।",
      "आप महान लचीलेपन में सक्षम हैं।",
      "आपमें सहने की शक्ति है।",
      "आप संवेदनशीलता में साहस खोज रहे हैं।",
      "आपके पास आंतरिक शक्ति है जिसे आपने अभी तक नहीं आज़माया है।",
      "आप बहादुर बनना सीख रहे हैं।",
      "आपमें खुद बने रहने का साहस है।",
      "आप अपने संघर्षों से अधिक मजबूत हैं।",
      "आपमें फिर से उठने की ताकत है।",
      "आप अपनी ताकत पर भरोसा करना सीख रहे हैं।",
      "आपके दिल में साहस है।",
      "आप मानसिक दृढ़ता बना रहे हैं।",
      "आपके पास डटे रहने की शक्ति है।",
      "आप सिर उठाकर खड़ा रहना सीख रहे हैं।",
      "आपकी आत्मा में शक्ति है।",
      "आप हर कदम के साथ और बहादुर बन रहे हैं।",
      "आपमें ठीक होने का साहस है।",
      "आप जितना जानते हैं उससे कहीं अधिक मजबूत हैं।",
      "आपकी आत्मा में लचीलापन है।",
      "आप निडर बनना सीख रहे हैं।",
      "आपमें जारी रखने की शक्ति है।",
      "आप यहाँ रहकर ही साहसी हैं।",
      "आप आनंद का अनुभव करने के पात्र हैं।",
      "आपके चारों ओर सुंदरता है।",
      "आप मुस्कुराने के कारण खोज सकते हैं।",
      "आपको खुश महसूस करने की अनुमति है।",
      "अच्छी चीजें आने वाली हैं।",
      "आप शांति के क्षणों के पात्र हैं।",
      "आप छोटी-छोटी खुशियों की सराहना कर सकते हैं।",
      "आप खुशी के पात्र हैं।",
      "आपके जीवन में रोशनी है।",
      "आप अच्छाई देखना चुन सकते हैं।",
      "आप आभारी महसूस करने के पात्र हैं।",
      "आप आशीर्वादों से घिरे हुए हैं।",
      "आप साधारण चीजों में आनंद पा सकते हैं।",
      "आप सुंदर क्षणों के पात्र हैं।",
      "आपके जीवन में अच्छाई है।",
      "आप जहाँ हैं वहाँ की सराहना कर सकते हैं।",
      "आप संतोष महसूस करने के पात्र हैं।",
      "आप विकास का अनुभव कर रहे हैं।",
      "आप छोटी जीत का जश्न मना सकते हैं।",
      "आप उत्सव के पात्र हैं।",
      "आशावादी होने के कारण मौजूद हैं।",
      "आप सकारात्मक क्षणों को अपना सकते हैं।",
      "आप शांति महसूस करने के पात्र हैं।",
      "आप प्यार से घिरे हुए हैं।",
      "आप रोज़ कृतज्ञता पा सकते हैं।",
      "आप अच्छे अनुभवों के पात्र हैं।",
      "खुशी आपका इंतज़ार कर रही है।",
      "आप अपनी यात्रा की सराहना कर सकते हैं।",
      "आप पूर्ण महसूस करने के पात्र हैं।",
      "आप जीवन को खूबसूरती से जी रहे हैं।",
      "आप इसमें अकेले नहीं हैं।",
      "ऐसे लोग हैं जो परवाह करते हैं।",
      "आप समर्थन और मदद के पात्र हैं।",
      "ज़रूरत पड़ने पर आप संपर्क कर सकते हैं।",
      "आप संबंध के पात्र हैं।",
      "आप सुने जाने के पात्र हैं।",
      "आप अपने संघर्षों को साझा कर सकते हैं।",
      "आप समझ के पात्र हैं।",
      "आप दूसरों से करुणा के पात्र हैं।",
      "आप अपनी ज़रूरत की चीज़ मांग सकते हैं।",
      "आप समुदाय के पात्र हैं।",
      "आप समर्थित महसूस करने के पात्र हैं।",
      "आप दूसरों पर भरोसा कर सकते हैं।",
      "आप दोस्ती के पात्र हैं।",
      "आप देखे जाने के पात्र हैं।",
      "आप दूसरों से जुड़ सकते हैं।",
      "आप दयालुता के पात्र हैं।",
      "आप शामिल महसूस करने के पात्र हैं।",
      "आप सार्थक रिश्ते बना सकते हैं।",
      "आप प्यार के पात्र हैं।",
      "आप मूल्यवान महसूस करने के पात्र हैं।",
      "आप समर्थन दे और प्राप्त कर सकते हैं।",
      "आप अपनेपन के पात्र हैं।",
      "आप जुड़ाव महसूस करने के पात्र हैं।",
      "आप रिश्तों में भरोसा कर सकते हैं।",
      "आप देखभाल के पात्र हैं।",
      "आप समझे जाने के पात्र हैं।",
      "आप अपना समूह खोज सकते हैं।",
      "आप साथ के पात्र हैं।",
      "आप स्वस्थ संबंधों के पात्र हैं।",
      "आपके जीवन का उद्देश्य है।",
      "आप फर्क पैदा करते हैं।",
      "आपकी उपस्थिति मायने रखती है।",
      "आपके पास देने के लिए अद्वितीय उपहार हैं।",
      "आपकी कहानी महत्वपूर्ण है।",
      "आप एक कारण से यहाँ हैं।",
      "आपकी यात्रा का अर्थ है।",
      "आप दुनिया में योगदान देते हैं।",
      "आपका अस्तित्व मूल्यवान है।",
      "आपकी एक भूमिका है।",
      "आपका जीवन दूसरों को छूता है।",
      "आप प्रभाव डाल रहे हैं।",
      "आपकी आवाज़ सुने जाने योग्य है।",
      "आपके पास योगदान देने के लिए कुछ है।",
      "आपके अनुभव मायने रखते हैं।",
      "आप अपनी विरासत बना रहे हैं।",
      "आपके कार्यों का अर्थ है।",
      "आप किसी बड़ी चीज़ का हिस्सा हैं।",
      "आपके जीवन का महत्व है।",
      "आप एक सार्थक जीवन के पात्र हैं।",
      "आपका दृष्टिकोण मूल्यवान है।",
      "आप अपना उद्देश्य खोज रहे हैं।",
      "आपकी उपस्थिति एक उपहार है।",
      "आप इरादे के साथ जी रहे हैं।",
      "आपकी यात्रा दूसरों को प्रेरित करती है।",
      "आप अपनी पहचान बना रहे हैं।",
      "आपका जीवन सार्थक है।",
      "आप सकारात्मक बदलाव ला रहे हैं।",
      "आपका अस्तित्व गहराई से मायने रखता है।",
      "आप अपना उद्देश्य पूरा कर रहे हैं।",
      "आप उसे छोड़ सकते हैं जो अब आपके काम का नहीं है।",
      "आप स्वतंत्र महसूस करने के पात्र हैं।",
      "आप पुराने ढर्रों को छोड़ सकते हैं।",
      "आपको आगे बढ़ने की अनुमति है।",
      "आप भारमुक्त महसूस करने के पात्र हैं।",
      "आप खुद को माफ कर सकते हैं।",
      "आप छोड़ना सीख रहे हैं।",
      "आप अपराधबोध से मुक्ति के पात्र हैं।",
      "आप उस चीज़ को छोड़ सकते हैं जो आपको नीचे गिराती है।",
      "आपको हल्का महसूस करने की अनुमति है।",
      "आप आज़ाद होने के पात्र हैं।",
      "आप अतीत को पीछे छोड़ सकते हैं।",
      "आप नियंत्रण छोड़ना सीख रहे हैं।",
      "आप मुक्त महसूस करने के पात्र हैं।",
      "आप पूर्णता के विचार को छोड़ सकते हैं।",
      "आपको समर्पण करने की अनुमति है।",
      "आप शर्म से मुक्ति के पात्र हैं।",
      "आप उम्मीदों को छोड़ सकते हैं।",
      "आप माफ करना सीख रहे हैं।",
      "आप भारमुक्त महसूस करने के पात्र हैं।",
      "आप निर्णय लेना छोड़ सकते हैं।",
      "आपको स्वतंत्र होने की अनुमति है।",
      "आप दर्द से मुक्ति के पात्र हैं।",
      "आप उसे समर्पित कर सकते हैं जिसे आप बदल नहीं सकते।",
      "आप स्वीकार करना सीख रहे हैं।",
      "आप खुद बने रहने की आज़ादी के पात्र हैं।",
      "आप पुराने घावों को छोड़ सकते हैं।",
      "आपको ठीक होने की अनुमति है।",
      "आप शांति महसूस करने के पात्र हैं।",
      "आप छोड़ सकते हैं और भरोसा कर सकते हैं।",
      "हर दिन आपको कुछ नया सिखाता है।",
      "आप ज्ञान प्राप्त कर रहे हैं।",
      "आप हर अनुभव से सीखते हैं।",
      "आप अधिक जागरूक हो रहे हैं।",
      "आप चुनौतियों के माध्यम से बढ़ते हैं।",
      "आप अपने बारे में सीख रहे हैं।",
      "आप संघर्षों से अंतर्दृष्टि प्राप्त करते हैं।",
      "आप समझ विकसित कर रहे हैं।",
      "आप सुख और दुख दोनों के माध्यम से सीखते हैं।",
      "आप अधिक बुद्धिमान बन रहे हैं।",
      "आप गलतियों से बढ़ते हैं।",
      "आप जीवन के सबक सीख रहे हैं।",
      "आप अनुभव के माध्यम से स्पष्टता प्राप्त करते हैं।",
      "आप अपने ज्ञान का विस्तार कर रहे हैं।",
      "आप हर पल से सीखते हैं।",
      "आप दृष्टिकोण विकसित कर रहे हैं।",
      "आप सीखने के माध्यम से ताकत प्राप्त करते हैं।",
      "आप अधिक सचेत हो रहे हैं।",
      "आप सीखते हैं कि वास्तव में क्या मायने रखता है।",
      "आप जागरूकता में बढ़ रहे हैं।",
      "आप चिंतन के माध्यम से ज्ञान प्राप्त करते हैं।",
      "आप भरोसा करना सीख रहे हैं।",
      "आप अनुभव के माध्यम से सत्य की खोज करते हैं।",
      "आप अधिक जागरूक बन रहे हैं।",
      "आप हर मौसम से सीखते हैं।",
      "आप गहरी समझ प्राप्त कर रहे हैं।",
      "आप चिंतन के माध्यम से बढ़ते हैं।",
      "आप सीख रहे हैं कि आपको क्या चाहिए।",
      "आप स्थिरता के माध्यम से अंतर्दृष्टि प्राप्त करते हैं।",
      "आप वह बन रहे हैं जो आपको होना चाहिए।",
      "आप अपनी प्रगति का जश्न मनाने के पात्र हैं।",
      "आपने बहुत कुछ हासिल किया है।",
      "आप मान्यता के पात्र हैं।",
      "आप अपनी यात्रा का सम्मान करने के पात्र हैं।",
      "आप जबरदस्त रूप से बढ़े हैं।",
      "आप उत्सव के पात्र हैं।",
      "आप अपनी प्रगति को स्वीकार करने के पात्र हैं।",
      "आपने अविश्वसनीय बाधाओं को पार किया है।",
      "आप गर्व के पात्र हैं।",
      "आप खुद का जश्न मनाने के पात्र हैं।",
      "आपने अपनी सोच से ज़्यादा हासिल किया है।",
      "आप प्रशंसा के पात्र हैं।",
      "आप अपनी ताकत को पहचानने के पात्र हैं।",
      "आप बहुत कुछ झेलकर यहाँ तक आए हैं।",
      "आप बधाई के पात्र हैं।",
      "आप गर्व महसूस करने के पात्र हैं।",
      "आपने अद्भुत लचीलापन दिखाया है।",
      "आप सम्मान के पात्र हैं।",
      "आप अपनी जीत का जश्न मनाने के पात्र हैं।",
      "आपने साहस दिखाया है।",
      "आप प्रशंसा के पात्र हैं।",
      "आप अपना मूल्य पहचानने के पात्र हैं।",
      "आपने अपनी ताकत साबित कर दी है।",
      "आप सराहना के पात्र हैं।",
      "आप अपने अस्तित्व का जश्न मनाने के पात्र हैं।",
      "आपने एक सुंदर यात्रा बनाई है।",
      "आप प्यार aur प्रशंसा के पात्र हैं।",
      "आप पूर्ण महसूस करने के पात्र हैं।",
      "आप यहाँ तक आ गए हैं।",
      "आप सभी अच्छी चीजों के पात्र हैं।",
      "आपने एक और दिन पूरा कर लिया है।",
      "आप यहाँ हैं, और उतना ही काफी है।",
      "आप इस पल का जश्न मनाने के पात्र हैं।",
      "आपने पूरा चक्र पूरा कर लिया है।",
      "आप कल एक नई शुरुआत के पात्र हैं।"
    ],
    'hn': [
      "Aapko cheezon ko dheere karne ki permission hai.",
      "Har bura din kharab life nahi hoti.",
      "Rest karna theek hai. Aap lazy nahi hain.",
      "Aapko aaj hi sab kuch theek karne ki zaroorat nahi.",
      "Yahan hona hi kaafi hai.",
      "Aapki feelings valid hain, chahe koi na samjhe.",
      "Progress hamesha dikhti nahi.",
      "Aap jitna sochte hain usse behtar kar rahe hain.",
      "Help mangna theek hai.",
      "Aap gentleness deserve karte hain, khas kar khud se.",
      "Chhote kadam bhi aage badhne wale kadam hain.",
      "Aap toote hue nahi hain. Aap ek human hain.",
      "Theek na hona bhi theek hai.",
      "Aapki struggles aapko define nahi karti.",
      "Aapne apne 100% sabse bure dino ko survive kiya hai.",
      "Healing hamesha ek seedhi line nahi hoti.",
      "Aap pyaar aur care deserve karte hain.",
      "Boundaries set karna theek hai.",
      "Aapka kisi ko explanation dena nahi banta.",
      "Aapki speed aapke liye perfect hai.",
      "Aapko apna man badalne ki permission hai.",
      "Khud ko priority dena theek hai.",
      "Aap jaise hain, waise hi kaafi hain.",
      "Aapka mental health matter karta hai.",
      "Aap kisi par bojh nahi hain.",
      "Apni emotions ko feel karna theek hai.",
      "Aap jitna jaante hain usse zyada strong hain.",
      "Aap patience aur understanding deserve karte hain.",
      "Phir se shuru karna theek hai.",
      "Aap achhi cheezon ke haqdaar hain."
    ],
  };

  static String today(String lang) {
    final dayOfYear =
        DateTime.now().difference(DateTime(DateTime.now().year, 1, 1)).inDays;
    final thoughts = localizedThoughts[lang] ?? localizedThoughts['en']!;
    return thoughts[dayOfYear % thoughts.length];
  }
}
